#!/bin/bash

# Help page
showHelp() {
    cat << EOF
Usage: ./landscaper -i <input-file> -o <output-directory> [--cores/--seed/--group/--colnames/--coordinate/--covariate/--input_sparse/--memgb/-h/-v]
Landscaper: Snakemake workflow to perform Energy Landscape Analysis

    -i, -input,         --input                 Input file (e.g., data/testdata.tsv, mandatory)

    -o, -outdir,        --outdir                Output directory (e.g., output, mandatory)

    -c, -cores,         --cores                 Number of cores to use Snakemake (Default value is 10, optional)

    -s, -seed,          --seed                  Random seed used when visualize status network (Default value is 123456) (optional)

    -g, -group,      --group                    Group of input matrix (Default value is "None") (optional)

    -l, -colnames,      --colnames              Column/variable names for data matrix (Default value is "None") (optional)

    -d, -coordinate,      --coordinate          2D Coordinates of states (e.g, t-SNE, UMAP) (Default value is "None") (optional)

    -e, -covariate,       --covariate          Covariate file of input data such as time points or experimental conditions (e.g., data/cov_data.tsv, optional)

    -p, -input_sparse,    --input_sparse       Whether the input data is formatted as Matrix Market <MM> (Default value is FALSE)

    -m, -memgb,         --memgb                 Memory usage (GB, e.g., default value is 10, optional)

    -h, -help,          --help                  Display help

    -v, -version,       --version               Version of this workflow

EOF
}

# Default Values
INPUT=""
OUTDIR=""
CORES=10
SEED=123456
GROUP="None"
COLNAMES="None"
COORDINATE="None"
COVARIATE="None"
INPUT_SPARSE="FALSE"
MEMGB=10
VERSION="v1.7.0"


# Command Argument Parsing
while getopts i:o:c:s:g:l:d:e:p:m:h-:v- opt; do
	optarg="$OPTARG"
	[[ "$opt" = - ]] &&
	    opt="-${OPTARG%%=*}" &&
	    optarg="${OPTARG/${OPTARG%%=*}/}" &&
	    optarg="${optarg#=}"
    case "-$opt" in
        -i|--input)
            INPUT="$optarg"
            ;;
        -o|--outdir)
            OUTDIR="$optarg"
            ;;
        -c|--cores)
            CORES="$optarg"
            ;;
        -s|--seed)
            SEED="$optarg"
            ;;
        -g|--group)
            GROUP="$optarg"
            ;;
        -l|--colnames)
            COLNAMES="$optarg"
            ;;
        -d|--corrdinate)
            COORDINATE="$optarg"
            ;;
        -e|--covariate)
            COVARIATE="$optarg"
            ;;
        -p|--input_sparse)
            INPUT_SPARSE="$optarg"
            ;;
        -m|--memgb)
            MEMGB="$optarg"
            ;;
        -h|--help)
            showHelp
            exit 0
            ;;
        -v|--version)
            echo $VERSION
            exit 0
            ;;
        \?)
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

# Perform Snakemake Workflow
snakemake -j $CORES --config input=$INPUT outdir=$OUTDIR \
seed=$SEED group=$GROUP colnames=$COLNAMES \
coordinate=$COORDINATE \
covariate=$COVARIATE input_sparse=$INPUT_SPARSE \
--resources mem_gb=$MEMGB
