name: Docker Pull/Run (koki/landscaper_component)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
    unit-test-job:
        name: run unit-test job
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: docker run
              run: |
                  docker run koki/landscaper_component:latest R -e "library('dcTensor'); library('IsingSampler'); library('igraph'); library('tidyverse'); library('RColorBrewer'); library('akima'); library('spatstat'); library('magick'); library('cowplot'); library('dendextend')" && python3 -c "import snakemake; import sys; import numpy as np" && snakemake -v