name: Docker Pull/Run (ghcr.io/chiba-ai-med/landscaper)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
    unit-test-job:
        name: run unit-test job
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: docker run
              run: |
                  echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u kokitsuyuzaki --password-stdin && docker pull ghcr.io/chiba-ai-med/landscaper:main
